# Generated by Django 4.2.7 on 2023-12-03 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseinworkout',
            old_name='exercise',
            new_name='exercise_id',
        ),
    ]
