# Generated by Django 4.2.7 on 2023-11-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='body_part',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_id',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='gif_url',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='secondary_muscles',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='target',
        ),
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(),
        ),
    ]
