# Generated by Django 4.2.7 on 2023-11-28 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_remove_exercise_body_part_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
