# Generated by Django 4.2.7 on 2023-12-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_rename_exercise_exerciseinworkout_exercise_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseinworkout',
            name='rest_time',
            field=models.IntegerField(default=0),
        ),
    ]
